# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [10]:
sinasc2=sinasc_raw[['munResNome','IDADEMAE','IDADEPAI']]
sinasc2.groupby('munResNome').median()

                           IDADEMAE  IDADEPAI
munResNome
Alta Floresta D'Oeste          25.0      28.5
Alto Alegre dos Parecis        25.0      28.0
Alto Paraíso                   24.0      25.5
Alvorada D'Oeste               25.0      31.0
Ariquemes                      25.0      29.0
Buritis                        25.0      28.5
Cabixi                         26.0      35.5
Cacaulândia                    25.0      33.5
Cacoal                         26.0      30.0
Campo Novo de Rondônia         25.0      29.5
Candeias do Jamari             25.0      30.0
Castanheiras                   27.0      31.5
Cerejeiras                     27.0      32.0
Chupinguaia                    25.0      29.0
Colorado do Oeste              28.0      34.0
Corumbiara                     24.0      30.0
Costa Marques                  23.0      28.5
Cujubim                        23.0      34.5
Espigão D'Oeste                26.0      31.0
Governador Jorge Teixeira      24.0      28.0
Guajará-Mirim                  24.0      30.0
Itapuã do Oeste                26.0      40.0
Jaru                           25.0      31.0
Ji-Paraná                      26.0      30.0
Machadinho D'Oeste             25.0      31.0
Ministro Andreazza             28.0      33.0
Mirante da Serra               26.0      32.0
Monte Negro                    25.0      36.0
Município ignorado - RO        24.0      22.0
Nova Brasilândia D'Oeste       25.0      29.0
Nova Mamoré                    25.0      32.0
Nova União                     26.5      30.0
Novo Horizonte do Oeste        26.0      30.0
Ouro Preto do Oeste            26.0      31.0
Parecis                        26.0      32.0
Pimenta Bueno                  25.0      29.0
Pimenteiras do Oeste           25.0      36.0
Porto Velho                    26.0      32.0
Presidente Médici              25.0      29.0
Primavera de Rondônia          26.0      33.0
Rio Crespo                     26.5      28.0
Rolim de Moura                 26.0      29.0
Santa Luzia D'Oeste            26.0      30.0
Seringueiras                   24.0      29.0
São Felipe D'Oeste             25.5      29.5
São Francisco do Guaporé       25.0      31.0
São Miguel do Guaporé          26.0      32.0
Teixeirópolis                  26.0      29.5
Theobroma                      24.0      28.5
Urupá                          27.0      30.0
Vale do Anari                  26.0      34.0
Vale do Paraíso                26.0      30.0
Vilhena                        26.0      34.0

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [26]:
sinasc_aniv=sinasc_raw[sinasc_raw['DTNASC']=='2019-01-22']
sinasc_aniv.groupby(['SEXO','ESCMAE'])['PESO'].mean()

SEXO       ESCMAE
Feminino   12 anos ou mais    3304.375000
           4 a 7 anos         3313.200000
           8 a 11 anos        2918.846154
Masculino  1 a 3 anos         3915.000000
           12 anos ou mais    3465.000000
           4 a 7 anos         3546.250000
           8 a 11 anos        3194.052632
Name: PESO, dtype: float64

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [37]:
result = sinasc_raw['munResNome'].value_counts()
result

Porto Velho                  8437
Ji-Paraná                    2182
Ariquemes                    1729
Vilhena                      1590
Cacoal                       1374
Rolim de Moura                927
Jaru                          881
Guajará-Mirim                 781
Ouro Preto do Oeste           631
Pimenta Bueno                 616
Buritis                       583
Machadinho D'Oeste            500
Espigão D'Oeste               450
Nova Mamoré                   432
Alta Floresta D'Oeste         367
São Miguel do Guaporé         353
Candeias do Jamari            337
Presidente Médici             304
São Francisco do Guaporé      303
Nova Brasilândia D'Oeste      261
Cerejeiras                    237
Costa Marques                 233
Alto Paraíso                  226
Colorado do Oeste             214
Alvorada D'Oeste              205
Cujubim                       205
Monte Negro                   199
Urupá                         170
Seringueiras                  168
Campo Novo de Rondônia        166
Mirante da Serra              164
Chupinguaia                   162
Alto Alegre dos Parecis       154
Corumbiara                    127
Governador Jorge Teixeira     112
Itapuã do Oeste               109
Nova União                    104
Santa Luzia D'Oeste            99
Novo Horizonte do Oeste        98
Theobroma                      97
Vale do Anari                  93
Ministro Andreazza             84
Vale do Paraíso                81
Cabixi                         80
Cacaulândia                    75
Teixeirópolis                  64
São Felipe D'Oeste             54
Rio Crespo                     50
Parecis                        44
Primavera de Rondônia          43
Pimenteiras do Oeste           40
Castanheiras                   32
Município ignorado - RO         1
Name: munResNome, dtype: int64

In [38]:
#menos bebes : Castanheiras
sinasc_cast=sinasc_raw[sinasc_raw['munResNome']=='Castanheiras']
sinasc_cast.groupby('munResNome').aggregate({'IDADEMAE': 'min', 'IDADEPAI': 'max'})

              IDADEMAE  IDADEPAI
munResNome
Castanheiras        17      43.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

In [55]:
sinasc_mar=sinasc_raw.loc[((sinasc_raw['DTNASC']<='2019-03-31') & (sinasc_raw['DTNASC']>='2019-03-01'))]
result = sinasc_mar['munResNome'].value_counts()
result

Porto Velho                  744
Ji-Paraná                    188
Vilhena                      148
Ariquemes                    141
Cacoal                       133
Jaru                          80
Guajará-Mirim                 75
Rolim de Moura                69
Ouro Preto do Oeste           67
Pimenta Bueno                 62
Buritis                       59
Nova Mamoré                   53
Machadinho D'Oeste            44
Espigão D'Oeste               44
São Miguel do Guaporé         41
Candeias do Jamari            33
São Francisco do Guaporé      31
Alta Floresta D'Oeste         31
Presidente Médici             29
Costa Marques                 24
Alto Paraíso                  22
Alvorada D'Oeste              22
Monte Negro                   20
Nova Brasilândia D'Oeste      20
Seringueiras                  19
Colorado do Oeste             19
Chupinguaia                   18
Cujubim                       17
Cerejeiras                    16
Urupá                         14
Vale do Paraíso               13
Campo Novo de Rondônia        13
Corumbiara                    12
Vale do Anari                 11
Governador Jorge Teixeira     10
Alto Alegre dos Parecis       10
Cacaulândia                   10
Mirante da Serra               9
Rio Crespo                     9
Theobroma                      8
Itapuã do Oeste                8
Santa Luzia D'Oeste            7
Nova União                     7
Pimenteiras do Oeste           6
Cabixi                         6
Parecis                        6
Ministro Andreazza             6
Primavera de Rondônia          5
Novo Horizonte do Oeste        5
São Felipe D'Oeste             5
Castanheiras                   4
Teixeirópolis                  3
Name: munResNome, dtype: int64

In [56]:
#Municpio que mais nasceu em Março: Porto Velho
sinasc_por=sinasc_mar[sinasc_mar['munResNome']=='Porto Velho']
#qual a idade media, maxima, minima dos pais nesse municipio?
sinasc_por.groupby('munResNome').agg({'IDADEMAE':['min','max','mean'], 'IDADEPAI':['min','max','mean']})

            IDADEMAE                IDADEPAI
                 min max       mean      min   max       mean
munResNome
Porto Velho       14  44  26.596774     19.0  62.0  34.629032

In [57]:
#qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
sinasc_por.groupby('munResNome').agg({'QTDFILVIVO':['min','max','mean']})

            QTDFILVIVO
                   min  max      mean
munResNome
Porto Velho        0.0  9.0  1.295056

In [69]:
'''Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados.
Algo que você julgue relevante e novo pra você.'''
def top(df, n = 5, column = 'QTDFILVIVO'):
    return df.fillna(0).sort_values(by = column, ascending = False)[:5]

sinasc_2 = sinasc_por[['munResNome','IDADEMAE','IDADEPAI']]
sinasc_2.groupby('munResNome').describe()

            IDADEMAE                                                     \
               count       mean       std   min   25%   50%   75%   max
munResNome
Porto Velho    744.0  26.596774  6.764748  14.0  21.0  26.0  31.0  44.0

            IDADEPAI
               count       mean       std   min    25%   50%   75%   max
munResNome
Porto Velho     62.0  34.629032  8.789401  19.0  29.25  34.0  38.0  62.0

Concluindo pela distribuição dos quartis das idades das mães está entre 21 e 31 anos e idades dos pais está entre 29 e 38 anos

In [51]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [7]:
sinasc_raw.select_dtypes(exclude=['int64','float64'])

,ESCMAE,GESTACAO,GRAVIDEZ,PARTO,DTNASC,SEXO,RACACOR,DTCADASTRO,CODANOMAL,VERSAOSIST,DTRECEBIM,munResStatus,munResTipo,munResNome,munResUf
0,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-19,Masculino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
1,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-21,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
2,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-02-25,Feminino,Branca,2019-03-08,NaN,3.2.01,2019-03-08,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
3,12 anos ou mais,37 a 41 semanas,Única,Cesáreo,2019-03-20,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia
4,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-03-23,Feminino,Parda,2019-04-03,NaN,3.2.01,2019-04-09,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27023,12 anos ou mais,32 a 36 semanas,Única,Cesáreo,2019-12-13,Masculino,Branca,2020-09-28,NaN,3.2.01,2020-10-13,ATIVO,MUNIC,Vilhena,Rondônia
27024,8 a 11 anos,37 a 41 semanas,Única,Vaginal,2019-10-04,Masculino,Branca,2019-10-16,NaN,3.2.01,2019-10-21,ATIVO,MUNIC,Chupinguaia,Rondônia
27025,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-08-02,Masculino,Parda,2019-08-07,NaN,3.2.00,2019-08-07,ATIVO,MUNIC,Vilhena,Rondônia
27026,8 a 11 anos,32 a 36 semanas,Única,Vaginal,2019-12-23,Masculino,Parda,2020-01-07,NaN,3.2.00,2020-01-07,ATIVO,MUNIC,Vilhena,Rondônia
27027,8 a 11 anos,37 a 41 semanas,Única,Cesáreo,2019-12-27,Masculino,Parda,2020-10-15,NaN,3.2.01,2020-10-16,ATIVO,MUNIC,Novo Horizonte do Oeste,Rondônia

In [4]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')